# Generated by Django 4.2.2 on 2023-06-29 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Valorantinicio', '0002_alter_profesionales_fecha_nacimiento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jugadoresvalorant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('equipo', models.CharField(max_length=100)),
                ('rol', models.CharField(choices=[('Duelista', 'Duelista'), ('Controlador', 'Controlador'), ('Iniciador', 'Iniciador'), ('Centinela', 'Centinela')], max_length=100)),
                ('nacionalidad', models.CharField(max_length=100)),
                ('edad', models.IntegerField()),
            ],
        ),
    ]
