# Generated by Django 4.2.2 on 2023-07-15 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Valorantinicio', '0003_jugadoresvalorant'),
    ]

    operations = [
        migrations.CreateModel(
            name='buscar_jugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='jugadoresvalorant',
            name='descripcion',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='profesionales',
            name='descripcion',
            field=models.TextField(null=True),
        ),
    ]
